import { StyleSheet } from 'react-native';
import { theme } from '../../../core/theme/tokens';

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: theme.colors.background,
  },
  glowTop: {
    position: 'absolute',
    top: -110,
    left: -80,
    width: 260,
    height: 260,
    borderRadius: 260,
    backgroundColor: theme.colors.glow,
  },
  glowBottom: {
    position: 'absolute',
    right: -100,
    bottom: -130,
    width: 300,
    height: 300,
    borderRadius: 300,
    backgroundColor: theme.colors.glowSoft,
  },
  safeArea: {
    flexGrow: 1,
    paddingHorizontal: theme.spacing.lg,
  },
  layout: {
    flex: 1,
    justifyContent: 'space-between',
  },
  layoutLandscape: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: theme.spacing.xl,
  },
  hero: {
    alignItems: 'center',
  },
  heroLandscape: {
    flex: 1,
    justifyContent: 'center',
  },
  authColumn: {
    width: '100%',
  },
  authColumnLandscape: {
    flex: 1,
    maxWidth: 420,
    justifyContent: 'center',
  },
  logoFrame: {
    backgroundColor: theme.colors.surfaceSubtle,
    borderWidth: 1,
    borderColor: theme.colors.primaryBorder,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    shadowColor: theme.colors.shadow,
    shadowOffset: { width: 0, height: 18 },
    shadowOpacity: 0.48,
    shadowRadius: 28,
    elevation: 10,
  },
  logoImage: {
    width: '86%',
    height: '86%',
  },
  logoWordmarkBand: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: theme.colors.surfaceOverlay,
    borderTopWidth: 1,
    borderTopColor: theme.colors.primaryBorder,
  },
  logoWordmark: {
    color: theme.colors.primary,
    fontWeight: '900',
    letterSpacing: 3.2,
  },
  kicker: {
    color: theme.colors.primary,
    fontWeight: '800',
    textAlign: 'center',
    letterSpacing: 0.2,
  },
  title: {
    color: theme.colors.text,
    fontWeight: '900',
    textAlign: 'center',
  },
  subtitle: {
    color: theme.colors.textSecondary,
    textAlign: 'center',
  },
  authCard: {
    backgroundColor: theme.colors.surface,
    borderRadius: 30,
    borderWidth: 1,
    borderColor: theme.colors.borderSubtle,
    shadowColor: theme.colors.shadow,
    shadowOffset: { width: 0, height: 16 },
    shadowOpacity: 0.36,
    shadowRadius: 26,
    elevation: 8,
  },
  sectionLabel: {
    color: theme.colors.textStrong,
    fontWeight: '900',
    textAlign: 'center',
  },
  errorBox: {
    paddingVertical: theme.spacing.sm,
    paddingHorizontal: theme.spacing.md,
    borderRadius: theme.radius.lg,
    borderWidth: 1,
    borderColor: theme.colors.dangerBorder,
    backgroundColor: theme.colors.dangerFaded,
  },
  errorText: {
    color: theme.colors.danger,
    fontSize: theme.typography.size.sm,
    fontWeight: '700',
    textAlign: 'center',
  },
  authButton: {
    minHeight: 54,
    borderRadius: theme.radius.full,
    backgroundColor: theme.colors.primary,
    borderWidth: 1,
    borderColor: theme.colors.primary,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: theme.spacing.sm,
    paddingHorizontal: theme.spacing.lg,
    shadowColor: theme.colors.shadow,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.2,
    shadowRadius: 18,
    elevation: 4,
  },
  authButtonDisabled: {
    opacity: 0.48,
  },
  authButtonPressed: {
    opacity: 0.88,
  },
  googleIcon: {
    width: 26,
    height: 26,
  },
  authButtonText: {
    color: theme.colors.onPrimary,
    fontSize: theme.typography.size.md,
    fontWeight: '900',
  },
  newUserLine: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    flexWrap: 'wrap',
    gap: theme.spacing.xs,
  },
  newUserText: {
    color: theme.colors.textSecondary,
    fontSize: theme.typography.size.sm,
    fontWeight: '600',
    textAlign: 'center',
  },
  newUserAction: {
    color: theme.colors.textStrong,
    fontSize: theme.typography.size.sm,
    fontWeight: '900',
    textDecorationLine: 'underline',
  },
  dividerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.spacing.sm,
  },
  divider: {
    flex: 1,
    height: StyleSheet.hairlineWidth,
    backgroundColor: theme.colors.borderSubtle,
  },
  dividerText: {
    color: theme.colors.textMuted,
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 0.5,
  },
  futureOptions: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: theme.spacing.xl,
  },
  futureOption: {
    color: theme.colors.textMuted,
    fontSize: theme.typography.size.sm,
    fontWeight: '800',
  },
});
