import { ApiAuthError, assertTrustedWriteOrigin, requireAuthenticatedUser } from '@core/auth/requestAuth';
import prisma from '@core/data/client/PrismaClient';
import { NextRequest, NextResponse } from 'next/server';
import { withAuthCors } from '../auth/cors';
import { writeSecurityAudit } from '@core/security/audit';

export const runtime = 'nodejs';
export async function OPTIONS(request: NextRequest) { return withAuthCors(new NextResponse(null, { status: 204 }), request, 'POST, DELETE, OPTIONS'); }
const isExpoToken = (value: string) => /^(ExponentPushToken|ExpoPushToken)\[[A-Za-z0-9_-]{10,}\]$/.test(value);
export async function POST(request: NextRequest) { try { assertTrustedWriteOrigin(request); const user = await requireAuthenticatedUser(request); const body = await request.json() as { token?: unknown; platform?: unknown }; const token = typeof body.token === 'string' ? body.token.trim() : ''; const platform = body.platform; if (!isExpoToken(token) || (platform !== 'android' && platform !== 'ios')) return withAuthCors(NextResponse.json({ error: 'Invalid push device' }, { status: 400 }), request); const device = await prisma.pushDevice.upsert({ where: { token }, create: { userId: user.id, token, platform }, update: { userId: user.id, platform, lastSeenAt: new Date(), revokedAt: null } }); await writeSecurityAudit({ request, actor: user, action: 'device.push_registered', outcome: 'success', targetType: 'push_device', targetId: device.id, metadata: { platform } }); return withAuthCors(NextResponse.json({ id: device.id }), request); } catch (error) { const status = error instanceof ApiAuthError ? error.status : 500; return withAuthCors(NextResponse.json({ error: status === 500 ? 'Unable to register device' : error instanceof Error ? error.message : 'Unauthorized' }, { status }), request); } }
export async function DELETE(request: NextRequest) { try { assertTrustedWriteOrigin(request); const user = await requireAuthenticatedUser(request); const body = await request.json() as { token?: unknown }; const token = typeof body.token === 'string' ? body.token.trim() : ''; const updated = await prisma.pushDevice.updateMany({ where: { userId: user.id, token }, data: { revokedAt: new Date() } }); await writeSecurityAudit({ request, actor: user, action: 'device.push_revoked', outcome: 'success', targetType: 'push_device', metadata: { count: updated.count } }); return withAuthCors(NextResponse.json({ ok: true }), request); } catch (error) { const status = error instanceof ApiAuthError ? error.status : 500; return withAuthCors(NextResponse.json({ error: status === 500 ? 'Unable to revoke device' : error instanceof Error ? error.message : 'Unauthorized' }, { status }), request); } }
