import { StyleSheet } from 'react-native';
import { theme } from '../../../core/theme/tokens';

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: theme.colors.background,
  },
  content: {
    flexGrow: 1,
    paddingHorizontal: theme.spacing.lg,
    paddingBottom: theme.spacing.xl,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: theme.spacing.lg,
  },
  brandBlock: {
    alignItems: 'center',
  },
  eyebrow: {
    color: theme.colors.primary,
    fontSize: theme.typography.size.xs,
    fontWeight: '900',
    textTransform: 'uppercase',
    letterSpacing: 0,
  },
  title: {
    color: theme.colors.text,
    fontSize: theme.typography.size.xl,
    fontWeight: '900',
    lineHeight: theme.typography.size.xl * theme.typography.lineHeight.tight,
  },
  card: {
    flex: 1,
    minHeight: 500,
    borderRadius: theme.radius.xxl,
    backgroundColor: theme.colors.surface,
    overflow: 'hidden',
    shadowColor: theme.colors.shadow,
    shadowOffset: { width: 0, height: 18 },
    shadowOpacity: 0.18,
    shadowRadius: 24,
    elevation: 8,
  },
  image: {
    width: '100%',
    height: '62%',
    backgroundColor: theme.colors.surfaceAlt,
  },
  cardBody: {
    flex: 1,
    padding: theme.spacing.lg,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: theme.spacing.md,
  },
  name: {
    color: theme.colors.text,
    fontSize: theme.typography.size.xxl,
    fontWeight: '900',
    lineHeight: theme.typography.size.xxl * theme.typography.lineHeight.tight,
  },
  breed: {
    color: theme.colors.textSecondary,
    fontSize: theme.typography.size.md,
    fontWeight: '700',
    marginTop: theme.spacing.xs,
  },
  bio: {
    color: theme.colors.textSecondary,
    fontSize: theme.typography.size.md,
    lineHeight: theme.typography.size.md * theme.typography.lineHeight.normal,
    marginTop: theme.spacing.md,
  },
  traitRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: theme.spacing.sm,
    marginTop: theme.spacing.md,
  },
  trait: {
    backgroundColor: theme.colors.primaryFaded,
    borderRadius: theme.radius.full,
    paddingHorizontal: theme.spacing.md,
    paddingVertical: theme.spacing.sm,
  },
  traitText: {
    color: theme.colors.primaryDark,
    fontSize: theme.typography.size.sm,
    fontWeight: '800',
  },
  statPill: {
    minHeight: 44,
    paddingHorizontal: theme.spacing.md,
    borderRadius: theme.radius.full,
    backgroundColor: theme.colors.successFaded,
    alignItems: 'center',
    justifyContent: 'center',
  },
  statPillText: {
    color: theme.colors.success,
    fontSize: theme.typography.size.sm,
    fontWeight: '900',
  },
  actions: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: theme.spacing.lg,
    marginTop: theme.spacing.xl,
  },
  actionButtonLarge: {
    width: 64,
    height: 64,
  },
  emptyState: {
    flex: 1,
    minHeight: 460,
    alignItems: 'center',
    justifyContent: 'center',
    padding: theme.spacing.xl,
    backgroundColor: theme.colors.surface,
    borderRadius: theme.radius.xxl,
  },
  emptyTitle: {
    color: theme.colors.text,
    fontSize: theme.typography.size.xl,
    fontWeight: '900',
    textAlign: 'center',
  },
  emptyText: {
    color: theme.colors.textSecondary,
    fontSize: theme.typography.size.md,
    lineHeight: theme.typography.size.md * theme.typography.lineHeight.normal,
    textAlign: 'center',
    marginVertical: theme.spacing.lg,
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: theme.colors.overlay,
    alignItems: 'center',
    justifyContent: 'center',
    padding: theme.spacing.xl,
  },
  matchCard: {
    width: '100%',
    borderRadius: theme.radius.xxl,
    backgroundColor: theme.colors.surface,
    padding: theme.spacing.xl,
    alignItems: 'center',
  },
  matchTitle: {
    color: theme.colors.primary,
    fontSize: theme.typography.size.hero,
    fontWeight: '900',
    textAlign: 'center',
  },
  matchText: {
    color: theme.colors.textSecondary,
    fontSize: theme.typography.size.md,
    lineHeight: theme.typography.size.md * theme.typography.lineHeight.normal,
    marginVertical: theme.spacing.lg,
    textAlign: 'center',
  },
});
