import { StyleSheet } from 'react-native';
import { theme } from '../../../core/theme/tokens';

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: theme.colors.background,
  },
  safeArea: {
    flex: 1,
    width: '100%',
    maxWidth: theme.layout.maxPhoneWidth,
    alignSelf: 'center',
    paddingHorizontal: theme.spacing.lg,
  },
  header: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: theme.spacing.sm,
    marginBottom: theme.spacing.md,
  },
  headerSlot: {
    width: 96,
    alignItems: 'flex-end',
  },
  brandBlock: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  brandLogo: {
    width: 64,
    height: 64,
    borderRadius: theme.radius.lg,
    marginBottom: theme.spacing.xs,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: theme.colors.primaryBorder,
  },
  brandName: {
    color: theme.colors.primary,
    fontSize: theme.typography.size.xl,
    fontWeight: '900',
    letterSpacing: 1.8,
  },
  brandTagline: {
    color: theme.colors.textMuted,
    fontSize: theme.typography.size.xs,
    fontWeight: '800',
    letterSpacing: 1,
    marginTop: 2,
    textTransform: 'uppercase',
    textAlign: 'center',
  },
  headerActions: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: theme.spacing.sm,
  },
  profileChip: {
    alignItems: 'center',
    justifyContent: 'center',
    gap: 2,
  },
  profileAvatar: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: theme.colors.primaryFaded,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: theme.colors.border,
    overflow: 'hidden',
  },
  profileAvatarImage: {
    width: '100%',
    height: '100%',
  },
  profileAvatarText: {
    color: theme.colors.primaryDark,
    fontSize: theme.typography.size.sm,
    fontWeight: '900',
  },
  profileName: {
    color: theme.colors.text,
    fontSize: 11,
    fontWeight: '800',
    maxWidth: 48,
  },
  main: {
    flex: 1,
    justifyContent: 'space-between',
    paddingBottom: theme.spacing.md,
  },
  cardFrame: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: theme.spacing.sm,
  },
  card: {
    width: '100%',
    borderRadius: 30,
    backgroundColor: theme.colors.surface,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: theme.colors.borderStrong,
    shadowColor: theme.colors.shadow,
    shadowOffset: { width: 0, height: 18 },
    shadowOpacity: 0.16,
    shadowRadius: 26,
    elevation: 8,
  },
  cardImage: {
    width: '100%',
    backgroundColor: theme.colors.surfaceAlt,
  },
  cardBody: {
    flex: 1,
    paddingHorizontal: theme.spacing.lg,
    paddingTop: theme.spacing.md,
    paddingBottom: theme.spacing.lg,
    gap: theme.spacing.xs,
  },
  petName: {
    color: theme.colors.primary,
    fontSize: 30,
    fontWeight: '900',
    letterSpacing: 0.4,
    lineHeight: 34,
  },
  petMeta: {
    color: theme.colors.textSecondary,
    fontSize: theme.typography.size.xs,
    fontWeight: '800',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  },
  petBio: {
    color: theme.colors.text,
    fontSize: theme.typography.size.md,
    lineHeight: theme.typography.size.md * theme.typography.lineHeight.normal,
    marginTop: theme.spacing.xs,
  },
  actions: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: theme.spacing.sm,
    paddingTop: theme.spacing.md,
    paddingHorizontal: theme.spacing.xs,
  },
  actionItem: {
    minHeight: theme.layout.touchTarget,
    flex: 1,
    alignItems: 'center',
    justifyContent: 'flex-start',
    gap: theme.spacing.xs,
  },
  actionPressed: {
    opacity: 0.72,
  },
  actionButton: {
    width: 64,
    height: 64,
    borderRadius: 32,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: theme.colors.borderStrong,
    shadowColor: theme.colors.shadow,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.14,
    shadowRadius: 18,
    elevation: 5,
  },
  actionButtonSkip: {
    backgroundColor: theme.colors.surface,
  },
  actionButtonLike: {
    backgroundColor: theme.colors.primary,
    width: 70,
    height: 70,
    borderRadius: 35,
    borderColor: theme.colors.primary,
  },
  actionButtonSuper: {
    backgroundColor: theme.colors.surface,
  },
  actionLabel: {
    color: theme.colors.text,
    fontSize: 11,
    fontWeight: '900',
    textTransform: 'uppercase',
    letterSpacing: 0.3,
    textAlign: 'center',
  },
  emptyState: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: theme.spacing.md,
    paddingHorizontal: theme.spacing.xl,
  },
  emptyTitle: {
    color: theme.colors.text,
    fontSize: theme.typography.size.xl,
    fontWeight: '900',
    textAlign: 'center',
  },
  emptyText: {
    color: theme.colors.textSecondary,
    fontSize: theme.typography.size.md,
    lineHeight: theme.typography.size.md * theme.typography.lineHeight.normal,
    textAlign: 'center',
  },
  loadingBox: {
    minHeight: 440,
    alignItems: 'center',
    justifyContent: 'center',
    gap: theme.spacing.md,
  },
  loadingText: {
    color: theme.colors.textSecondary,
    fontSize: theme.typography.size.md,
    fontWeight: '700',
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: theme.colors.overlay,
    alignItems: 'center',
    justifyContent: 'center',
    padding: theme.spacing.xl,
  },
  matchCard: {
    width: '100%',
    borderRadius: 28,
    backgroundColor: theme.colors.surface,
    padding: theme.spacing.xl,
    alignItems: 'center',
    gap: theme.spacing.md,
  },
  matchTitle: {
    color: theme.colors.primary,
    fontSize: theme.typography.size.hero,
    fontWeight: '900',
    textAlign: 'center',
    letterSpacing: 0.4,
  },
  matchText: {
    color: theme.colors.textSecondary,
    fontSize: theme.typography.size.md,
    lineHeight: theme.typography.size.md * theme.typography.lineHeight.normal,
    textAlign: 'center',
  },
});
