import { ApiAuthError, assertTrustedWriteOrigin, requireAuthenticatedUser } from '@core/auth/requestAuth';
import prisma from '@core/data/client/PrismaClient';
import { NextRequest, NextResponse } from 'next/server';
import { withAuthCors } from '../auth/cors';
import { writeSecurityAudit } from '@core/security/audit';

export const runtime = 'nodejs';
export async function OPTIONS(request: NextRequest) { return withAuthCors(new NextResponse(null, { status: 204 }), request, 'GET, PUT, OPTIONS'); }
export async function GET(request: NextRequest) { try { const user = await requireAuthenticatedUser(request); const settings = await prisma.userSettings.findUnique({ where: { userId: user.id } }); return withAuthCors(NextResponse.json(settings), request); } catch (error) { const status = error instanceof ApiAuthError ? error.status : 500; return withAuthCors(NextResponse.json({ error: status === 500 ? 'Unable to load settings' : error instanceof Error ? error.message : 'Unauthorized' }, { status }), request); } }
export async function PUT(request: NextRequest) { try { assertTrustedWriteOrigin(request); const user = await requireAuthenticatedUser(request); const body = await request.json() as Record<string, unknown>; const themeMode = body.themeMode; const healthVisibility = body.healthVisibility; const notificationPreview = body.notificationPreview ?? 'generic'; const maxDistanceKm = Number(body.maxDistanceKm); if (!['dark','light','system'].includes(String(themeMode)) || !['connections','private'].includes(String(healthVisibility)) || !['generic','hidden'].includes(String(notificationPreview)) || !Number.isInteger(maxDistanceKm) || maxDistanceKm < 1 || maxDistanceKm > 250) return withAuthCors(NextResponse.json({ error: 'Invalid settings' }, { status: 400 }), request); const data = { themeMode: String(themeMode), healthVisibility: String(healthVisibility), notificationPreview: String(notificationPreview), maxDistanceKm, discoveryEnabled: Boolean(body.discoveryEnabled), showDistance: Boolean(body.showDistance), showOnlineStatus: Boolean(body.showOnlineStatus), readReceipts: Boolean(body.readReceipts), safetyCheckIns: Boolean(body.safetyCheckIns), lostPetAlerts: Boolean(body.lostPetAlerts), pushMessages: body.pushMessages !== false, pushRequests: body.pushRequests !== false, pushAppointments: body.pushAppointments !== false }; const settings = await prisma.userSettings.upsert({ where: { userId: user.id }, create: { userId: user.id, ...data }, update: data }); await writeSecurityAudit({ request, actor: user, action: 'settings.updated', outcome: 'success', targetType: 'user_settings', targetId: settings.id, metadata: { healthVisibility: String(healthVisibility), notificationPreview: String(notificationPreview) } }); return withAuthCors(NextResponse.json(settings), request); } catch (error) { const status = error instanceof ApiAuthError ? error.status : 500; return withAuthCors(NextResponse.json({ error: status === 500 ? 'Unable to save settings' : error instanceof Error ? error.message : 'Unauthorized' }, { status }), request); } }
